version: '3'
services: 
    web:
        stdin_open: true
        build: 
            context: .
            dockerfile: DockerFile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
    tests:
        stdin_open: true
        build:
            context: .
            dockerfile: DockerFile.dev
        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "start"]
        

        